### ISSUE TITLE
Start-Up Logos Overlap Header on Mouseover

### ISSUE THREAD

**Issue by ManickYoj** [olinfoundry/olinfoundry.github.com#2]
On the startup-fair page, if the page scrolls far enough that a logo is partially covered by the header and that logo is hovered over, the that logo appears in front of the header. Ideally, this would not be the case.

**Comment by EvanSimpson** [comment]
Add `z-index: 5000;` or equally high number here https://github.com/olinfoundry/olinfoundry.github.com/blob/master/style/foundryStyle.css#L61 and that ought to fix it.
